M48
; DRILL file {KiCad (6.0.2)} date Tue Sep  5 21:11:47 2023
; FORMAT={-:-/ absolute / inch / decimal}
; #@! TF.CreationDate,2023-09-05T21:11:47-07:00
; #@! TF.GenerationSoftware,Kicad,Pcbnew,(6.0.2)
; #@! TF.FileFunction,NonPlated,1,4,NPTH
FMAT,2
INCH
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T1C0.0591
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T2C0.0866
%
G90
G05
T1
X4.18Y-2.17
X4.4556Y-2.17
T2
X2.795Y-1.45
X2.795Y-2.65
X4.385Y-1.45
X4.385Y-2.65
T0
M30
